# Generated by Django 5.1.3 on 2024-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_validation_cycle_control_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='consulted_resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='date_elaborated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='control',
            name='status',
            field=models.CharField(default='Sin iniciar', max_length=50),
        ),
        migrations.AddField(
            model_name='control',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validation',
            name='person_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
