# Generated by Django 5.1.3 on 2024-11-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_control_consulted_resources_control_date_elaborated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designanswer',
            name='validation',
        ),
        migrations.AddField(
            model_name='designanswer',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designquestion',
            name='question',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='designanswer',
            name='answer',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No'), ('No Aplica', 'No Aplica')], max_length=20, null=True),
        ),
    ]
