# Generated by Django 5.1.3 on 2024-11-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_designanswer_validation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='execution_date',
        ),
    ]
